-- Barbosa's Delivery - Fase 22
-- Histórico de movimentações manuais e automáticas de estoque.

create table if not exists product_stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint,
  order_id text,
  cash_session_id text,
  movement_type text not null default 'manual_adjustment',
  quantity integer not null default 0,
  stock_before integer not null default 0,
  stock_after integer not null default 0,
  reason text,
  created_by text,
  created_at timestamp with time zone default now()
);

create index if not exists idx_product_stock_movements_product_id on product_stock_movements(product_id);
create index if not exists idx_product_stock_movements_order_id on product_stock_movements(order_id);
create index if not exists idx_product_stock_movements_created_at on product_stock_movements(created_at);
