-- Barbosa's Delivery - Fase 36
-- Botões por status, auditoria básica e motivos obrigatórios em ações sensíveis.

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_type text not null default 'system',
  user_name text not null default 'sistema',
  action text not null,
  entity text not null,
  entity_id text,
  before_json jsonb,
  after_json jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists app_errors (
  id bigint generated by default as identity primary key,
  source text not null,
  message text,
  stack text,
  metadata jsonb,
  created_at timestamp with time zone default now()
);

alter table orders add column if not exists reopened_at timestamp with time zone;
alter table orders add column if not exists reopened_by text;
alter table orders add column if not exists reopen_reason text;
alter table orders add column if not exists problem_reason text;
alter table orders add column if not exists problem_at timestamp with time zone;
alter table orders add column if not exists payment_confirmed_at timestamp with time zone;
alter table orders add column if not exists payment_confirmed_by text;

create index if not exists idx_audit_logs_created_at on audit_logs(created_at);
create index if not exists idx_audit_logs_entity on audit_logs(entity, entity_id);
create index if not exists idx_audit_logs_action on audit_logs(action);
create index if not exists idx_app_errors_created_at on app_errors(created_at);
