-- Barbosa's Delivery - Migração final de produção 6.0.47
-- Rode este arquivo no SQL Editor do Supabase antes do deploy final. Inclui correções da Fase 58 para cupons e estoque seguro.
-- Ele cria as tabelas principais caso o banco esteja novo e reforça colunas usadas pelo app.

create table if not exists products (
  id bigint primary key,
  name text not null default '',
  category text default '',
  price numeric not null default 0,
  cost numeric not null default 0,
  stock integer not null default 0,
  min_stock integer not null default 0,
  barcode text,
  expiration_date date,
  image_url text default '',
  has_variants boolean default false,
  variants jsonb default '[]'::jsonb,
  active boolean default true,
  deleted_at timestamp with time zone,
  paused_until timestamp with time zone,
  pause_reason text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists clients (
  id bigint primary key,
  name text not null default '',
  phone text default '',
  phone_digits text,
  cep text default '',
  street text default '',
  number text default '',
  district text default '',
  city text default '',
  state text default '',
  reference text default '',
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists couriers (
  id bigint primary key,
  name text not null default '',
  username text not null,
  password text not null default '',
  motorcycle_type text default 'Moto própria',
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists orders (
  id text primary key,
  cash_session_id text,
  origin_type text,
  tab_account_id bigint,
  order_type text default 'delivery',
  client text default '',
  customer_name text,
  phone text default '',
  address text default '',
  payment text default 'Pix',
  payment_status text default 'pending',
  payment_confirmed_at timestamp with time zone,
  payment_confirmed_by text,
  reopened_at timestamp with time zone,
  reopened_by text,
  reopen_reason text,
  change_for numeric,
  products_total numeric default 0,
  delivery_fee numeric default 0,
  discount numeric default 0,
  coupon_code text,
  coupon_id bigint,
  coupon_discount numeric default 0,
  courier_fee numeric default 0,
  store_fee numeric default 0,
  motorcycle_type text,
  value numeric default 0,
  estimated_delivery_minutes integer default 0,
  whatsapp_status text default 'not_sent',
  whatsapp_opened_at timestamp with time zone,
  whatsapp_sent_at timestamp with time zone,
  whatsapp_message text,
  status text default 'Aguardando retirada',
  origin text default 'store',
  needs_store_approval boolean default false,
  store_order_approved boolean default true,
  approved_at timestamp with time zone,
  reference text,
  delivery_district text,
  delivery_zone text,
  courier_username text default 'ALL',
  courier_name text default 'Todos os motoboys',
  notes text,
  picked_up_by_username text,
  picked_up_by_name text,
  picked_up_at timestamp with time zone,
  delivered_by_username text,
  delivered_by_name text,
  delivered_at timestamp with time zone,
  owner_approved boolean default false,
  owner_approved_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  accepted_by_username text,
  accepted_by_name text,
  accepted_at timestamp with time zone,
  refused_by_username text,
  refused_at timestamp with time zone,
  finalized_at timestamp with time zone,
  finalized_by text,
  problem_reason text,
  problem_at timestamp with time zone,
  proof_url text,
  delay_alerted_at timestamp with time zone,
  launched_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text,
  cash_session_id text,
  product_id bigint,
  name text default '',
  product_name text,
  quantity integer not null default 0,
  price numeric not null default 0,
  barcode text,
  is_kit boolean default false,
  kit_id bigint,
  created_at timestamp with time zone default now()
);

create table if not exists order_payments (
  id bigint generated by default as identity primary key,
  order_id text,
  cash_session_id text,
  method text not null default 'Outro',
  amount numeric not null default 0,
  status text not null default 'paid',
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists promotions (
  id bigint primary key,
  title text not null default '',
  description text default '',
  product_id bigint,
  badge text default 'Promoção da loja',
  image_url text default '',
  discount_percent numeric default 0,
  promotional_price numeric default 0,
  start_date date,
  end_date date,
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists coupons (
  id bigint primary key,
  code text not null unique,
  description text default '',
  discount_type text not null default 'fixed',
  discount_value numeric not null default 0,
  minimum_order_value numeric not null default 0,
  max_discount numeric not null default 0,
  usage_limit integer not null default 0,
  used_count integer not null default 0,
  start_date date,
  end_date date,
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists kits (
  id bigint primary key,
  name text not null default '',
  description text default '',
  price numeric not null default 0,
  end_date date,
  active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists kit_items (
  id bigint primary key,
  kit_id bigint,
  product_id bigint,
  quantity integer not null default 1,
  created_at timestamp with time zone default now()
);

create table if not exists store_settings (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists store_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  email text unique,
  password text not null,
  role text not null default 'operador',
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  type text,
  title text,
  message text,
  audience text,
  order_id text,
  courier_username text,
  customer_phone text,
  read_at timestamp with time zone,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table if not exists product_stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint,
  order_id text,
  cash_session_id text,
  movement_type text not null default 'manual_adjustment',
  quantity integer not null default 0,
  stock_before integer not null default 0,
  stock_after integer not null default 0,
  reason text,
  created_by text,
  created_at timestamp with time zone default now()
);

create table if not exists cash_sessions (
  id text primary key default gen_random_uuid()::text,
  status text not null default 'open',
  opening_amount numeric default 0,
  opened_at timestamp with time zone default now(),
  opened_by text,
  closed_at timestamp with time zone,
  closed_by text,
  total_sold numeric default 0,
  total_received numeric default 0,
  counted_cash numeric default 0,
  difference numeric default 0,
  pix_total numeric default 0,
  cash_total numeric default 0,
  debit_total numeric default 0,
  credit_total numeric default 0,
  pending_total numeric default 0,
  cancelled_total numeric default 0,
  closing_snapshot jsonb,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists cash_movements (
  id bigint primary key,
  movement_type text,
  type text,
  value numeric default 0,
  amount numeric default 0,
  reason text,
  opened_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists tab_accounts (
  id bigint primary key,
  customer_name text not null default 'Cliente',
  phone text default '',
  credit_limit numeric default 0,
  payment text default 'Dinheiro',
  status text default 'open',
  total numeric default 0,
  opened_at timestamp with time zone default now(),
  closed_at timestamp with time zone,
  closed_by text,
  cash_session_id text,
  items_json text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists tab_account_items (
  id bigint generated by default as identity primary key,
  tab_account_id bigint,
  product_id bigint,
  name text default '',
  quantity integer not null default 1,
  price numeric not null default 0,
  barcode text,
  created_at timestamp with time zone default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_type text not null default 'system',
  user_name text not null default 'sistema',
  action text not null,
  entity text not null,
  entity_id text,
  before_json jsonb,
  after_json jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists app_errors (
  id bigint generated by default as identity primary key,
  source text not null,
  message text,
  stack text,
  metadata jsonb,
  created_at timestamp with time zone default now()
);

-- Reforço de colunas caso o banco já existisse com esquema antigo.
-- Colunas-base reforçadas também para bancos muito antigos.
alter table products add column if not exists name text default '';
alter table products add column if not exists category text default '';
alter table products add column if not exists price numeric default 0;
alter table products add column if not exists cost numeric default 0;
alter table products add column if not exists stock integer default 0;
alter table products add column if not exists expiration_date date;
alter table products add column if not exists created_at timestamp with time zone default now();
alter table products add column if not exists updated_at timestamp with time zone default now();

alter table clients add column if not exists name text default '';
alter table clients add column if not exists phone text default '';
alter table clients add column if not exists cep text default '';
alter table clients add column if not exists street text default '';
alter table clients add column if not exists number text default '';
alter table clients add column if not exists district text default '';
alter table clients add column if not exists city text default '';
alter table clients add column if not exists state text default '';
alter table clients add column if not exists reference text default '';
alter table clients add column if not exists created_at timestamp with time zone default now();
alter table clients add column if not exists updated_at timestamp with time zone default now();

alter table couriers add column if not exists name text default '';
alter table couriers add column if not exists username text;
alter table couriers add column if not exists password text default '';
alter table couriers add column if not exists created_at timestamp with time zone default now();
alter table couriers add column if not exists updated_at timestamp with time zone default now();

alter table promotions add column if not exists title text default '';
alter table coupons add column if not exists code text;
alter table kits add column if not exists name text default '';

alter table products add column if not exists active boolean default true;
alter table products add column if not exists deleted_at timestamp with time zone;
alter table products add column if not exists has_variants boolean default false;
alter table products add column if not exists variants jsonb default '[]'::jsonb;
alter table products add column if not exists paused_until timestamp with time zone;
alter table products add column if not exists pause_reason text default '';
alter table products add column if not exists min_stock integer default 0;
alter table products add column if not exists barcode text;
alter table products add column if not exists image_url text default '';

alter table clients add column if not exists active boolean default true;
alter table clients add column if not exists deleted_at timestamp with time zone;
alter table clients add column if not exists phone_digits text;

alter table couriers add column if not exists active boolean default true;
alter table couriers add column if not exists deleted_at timestamp with time zone;
alter table couriers add column if not exists motorcycle_type text default 'Moto própria';

-- Reforço completo para bancos criados em fases antigas. O create table if not exists
-- não adiciona colunas quando a tabela já existe; por isso todas as colunas usadas
-- pelo app são garantidas aqui.
alter table orders add column if not exists cash_session_id text;
alter table orders add column if not exists origin_type text;
alter table orders add column if not exists tab_account_id bigint;
alter table orders add column if not exists order_type text default 'delivery';
alter table orders add column if not exists client text default '';
alter table orders add column if not exists customer_name text;
alter table orders add column if not exists phone text default '';
alter table orders add column if not exists address text default '';
alter table orders add column if not exists payment text default 'Pix';
alter table orders add column if not exists payment_status text default 'pending';
alter table orders add column if not exists payment_confirmed_at timestamp with time zone;
alter table orders add column if not exists payment_confirmed_by text;
alter table orders add column if not exists reopened_at timestamp with time zone;
alter table orders add column if not exists reopened_by text;
alter table orders add column if not exists reopen_reason text;
alter table orders add column if not exists change_for numeric;
alter table orders add column if not exists products_total numeric default 0;
alter table orders add column if not exists delivery_fee numeric default 0;
alter table orders add column if not exists discount numeric default 0;
alter table orders add column if not exists coupon_code text;
alter table orders add column if not exists coupon_id bigint;
alter table orders add column if not exists coupon_discount numeric default 0;
alter table orders add column if not exists courier_fee numeric default 0;
alter table orders add column if not exists store_fee numeric default 0;
alter table orders add column if not exists motorcycle_type text;
alter table orders add column if not exists value numeric default 0;
alter table orders add column if not exists estimated_delivery_minutes integer default 0;
alter table orders add column if not exists whatsapp_status text default 'not_sent';
alter table orders add column if not exists whatsapp_opened_at timestamp with time zone;
alter table orders add column if not exists whatsapp_sent_at timestamp with time zone;
alter table orders add column if not exists whatsapp_message text;
alter table orders add column if not exists status text default 'Aguardando retirada';
alter table orders add column if not exists origin text default 'store';
alter table orders add column if not exists needs_store_approval boolean default false;
alter table orders add column if not exists store_order_approved boolean default true;
alter table orders add column if not exists approved_at timestamp with time zone;
alter table orders add column if not exists reference text;
alter table orders add column if not exists delivery_district text;
alter table orders add column if not exists delivery_zone text;
alter table orders add column if not exists courier_username text default 'ALL';
alter table orders add column if not exists courier_name text default 'Todos os motoboys';
alter table orders add column if not exists notes text;
alter table orders add column if not exists picked_up_by_username text;
alter table orders add column if not exists picked_up_by_name text;
alter table orders add column if not exists picked_up_at timestamp with time zone;
alter table orders add column if not exists delivered_by_username text;
alter table orders add column if not exists delivered_by_name text;
alter table orders add column if not exists delivered_at timestamp with time zone;
alter table orders add column if not exists owner_approved boolean default false;
alter table orders add column if not exists owner_approved_at timestamp with time zone;
alter table orders add column if not exists cancelled_at timestamp with time zone;
alter table orders add column if not exists cancellation_reason text;
alter table orders add column if not exists accepted_by_username text;
alter table orders add column if not exists accepted_by_name text;
alter table orders add column if not exists accepted_at timestamp with time zone;
alter table orders add column if not exists refused_by_username text;
alter table orders add column if not exists refused_at timestamp with time zone;
alter table orders add column if not exists finalized_at timestamp with time zone;
alter table orders add column if not exists finalized_by text;
alter table orders add column if not exists problem_reason text;
alter table orders add column if not exists problem_at timestamp with time zone;
alter table orders add column if not exists proof_url text;
alter table orders add column if not exists delay_alerted_at timestamp with time zone;
alter table orders add column if not exists launched_at timestamp with time zone default now();
alter table orders add column if not exists created_at timestamp with time zone default now();
alter table orders add column if not exists updated_at timestamp with time zone default now();

alter table order_items add column if not exists cash_session_id text;
alter table order_items add column if not exists product_id bigint;
alter table order_items add column if not exists name text default '';
alter table order_items add column if not exists product_name text;
alter table order_items add column if not exists quantity integer default 0;
alter table order_items add column if not exists price numeric default 0;
alter table order_items add column if not exists barcode text;
alter table order_items add column if not exists is_kit boolean default false;
alter table order_items add column if not exists kit_id bigint;
alter table order_items add column if not exists created_at timestamp with time zone default now();

alter table order_payments add column if not exists cash_session_id text;
alter table order_payments add column if not exists method text default 'Outro';
alter table order_payments add column if not exists amount numeric default 0;
alter table order_payments add column if not exists status text default 'paid';
alter table order_payments add column if not exists notes text;
alter table order_payments add column if not exists created_at timestamp with time zone default now();

alter table promotions add column if not exists description text default '';
alter table promotions add column if not exists product_id bigint;
alter table promotions add column if not exists badge text default 'Promoção da loja';
alter table promotions add column if not exists image_url text default '';
alter table promotions add column if not exists discount_percent numeric default 0;
alter table promotions add column if not exists promotional_price numeric default 0;
alter table promotions add column if not exists start_date date;
alter table promotions add column if not exists end_date date;
alter table promotions add column if not exists active boolean default true;
alter table promotions add column if not exists deleted_at timestamp with time zone;
alter table promotions add column if not exists created_at timestamp with time zone default now();
alter table promotions add column if not exists updated_at timestamp with time zone default now();

alter table coupons add column if not exists description text default '';
alter table coupons add column if not exists discount_type text default 'fixed';
alter table coupons add column if not exists discount_value numeric default 0;
alter table coupons add column if not exists minimum_order_value numeric default 0;
alter table coupons add column if not exists max_discount numeric default 0;
alter table coupons add column if not exists usage_limit integer default 0;
alter table coupons add column if not exists used_count integer default 0;
alter table coupons add column if not exists start_date date;
alter table coupons add column if not exists end_date date;
alter table coupons add column if not exists active boolean default true;
alter table coupons add column if not exists created_at timestamp with time zone default now();
alter table coupons add column if not exists updated_at timestamp with time zone default now();

alter table kits add column if not exists description text default '';
alter table kits add column if not exists price numeric default 0;
alter table kits add column if not exists end_date date;
alter table kits add column if not exists created_at timestamp with time zone default now();
alter table kits add column if not exists updated_at timestamp with time zone default now();

alter table store_settings add column if not exists settings jsonb default '{}'::jsonb;
alter table store_settings add column if not exists created_at timestamp with time zone default now();
alter table store_settings add column if not exists updated_at timestamp with time zone default now();

alter table store_users add column if not exists email text;
alter table store_users add column if not exists password text default '';
alter table store_users add column if not exists role text default 'operador';
alter table store_users add column if not exists active boolean default true;
alter table store_users add column if not exists created_at timestamp with time zone default now();
alter table store_users add column if not exists updated_at timestamp with time zone default now();

alter table notifications add column if not exists type text;
alter table notifications add column if not exists title text;
alter table notifications add column if not exists message text;
alter table notifications add column if not exists audience text;
alter table notifications add column if not exists order_id text;
alter table notifications add column if not exists courier_username text;
alter table notifications add column if not exists customer_phone text;
alter table notifications add column if not exists read_at timestamp with time zone;
alter table notifications add column if not exists resolved_at timestamp with time zone;
alter table notifications add column if not exists created_at timestamp with time zone default now();

alter table product_stock_movements add column if not exists product_id bigint;
alter table product_stock_movements add column if not exists order_id text;
alter table product_stock_movements add column if not exists cash_session_id text;
alter table product_stock_movements add column if not exists movement_type text default 'manual_adjustment';
alter table product_stock_movements add column if not exists quantity integer default 0;
alter table product_stock_movements add column if not exists stock_before integer default 0;
alter table product_stock_movements add column if not exists stock_after integer default 0;
alter table product_stock_movements add column if not exists reason text;
alter table product_stock_movements add column if not exists created_by text;
alter table product_stock_movements add column if not exists created_at timestamp with time zone default now();

alter table cash_sessions add column if not exists status text default 'open';
alter table cash_sessions add column if not exists opening_amount numeric default 0;
alter table cash_sessions add column if not exists opened_at timestamp with time zone default now();
alter table cash_sessions add column if not exists opened_by text;
alter table cash_sessions add column if not exists closed_at timestamp with time zone;
alter table cash_sessions add column if not exists closed_by text;
alter table cash_sessions add column if not exists total_sold numeric default 0;
alter table cash_sessions add column if not exists total_received numeric default 0;
alter table cash_sessions add column if not exists counted_cash numeric default 0;
alter table cash_sessions add column if not exists difference numeric default 0;
alter table cash_sessions add column if not exists pix_total numeric default 0;
alter table cash_sessions add column if not exists cash_total numeric default 0;
alter table cash_sessions add column if not exists debit_total numeric default 0;
alter table cash_sessions add column if not exists credit_total numeric default 0;
alter table cash_sessions add column if not exists pending_total numeric default 0;
alter table cash_sessions add column if not exists cancelled_total numeric default 0;
alter table cash_sessions add column if not exists closing_snapshot jsonb;
alter table cash_sessions add column if not exists notes text;
alter table cash_sessions add column if not exists created_at timestamp with time zone default now();
alter table cash_sessions add column if not exists updated_at timestamp with time zone default now();

alter table cash_movements add column if not exists movement_type text;
alter table cash_movements add column if not exists type text;
alter table cash_movements add column if not exists value numeric default 0;
alter table cash_movements add column if not exists amount numeric default 0;
alter table cash_movements add column if not exists reason text;
alter table cash_movements add column if not exists opened_at timestamp with time zone;
alter table cash_movements add column if not exists notes text;
alter table cash_movements add column if not exists created_at timestamp with time zone default now();

alter table tab_accounts add column if not exists customer_name text default 'Cliente';
alter table tab_accounts add column if not exists phone text default '';
alter table tab_accounts add column if not exists credit_limit numeric default 0;
alter table tab_accounts add column if not exists payment text default 'Dinheiro';
alter table tab_accounts add column if not exists status text default 'open';
alter table tab_accounts add column if not exists total numeric default 0;
alter table tab_accounts add column if not exists opened_at timestamp with time zone default now();
alter table tab_accounts add column if not exists closed_at timestamp with time zone;
alter table tab_accounts add column if not exists closed_by text;
alter table tab_accounts add column if not exists cash_session_id text;
alter table tab_accounts add column if not exists items_json text;
alter table tab_accounts add column if not exists notes text;
alter table tab_accounts add column if not exists created_at timestamp with time zone default now();
alter table tab_accounts add column if not exists updated_at timestamp with time zone default now();

alter table tab_account_items add column if not exists tab_account_id bigint;
alter table tab_account_items add column if not exists product_id bigint;
alter table tab_account_items add column if not exists name text default '';
alter table tab_account_items add column if not exists quantity integer default 1;
alter table tab_account_items add column if not exists price numeric default 0;
alter table tab_account_items add column if not exists barcode text;
alter table tab_account_items add column if not exists created_at timestamp with time zone default now();


alter table kits add column if not exists active boolean default true;
alter table kit_items add column if not exists kit_id bigint;
alter table kit_items add column if not exists product_id bigint;
alter table kit_items add column if not exists quantity integer default 1;

insert into store_settings (id, settings)
values ('default', '{}'::jsonb)
on conflict (id) do nothing;

insert into store_users (name, username, email, password, role, active)
values ('Administrador da loja', 'gabrieladmin', null, 'B4rb@2026!', 'admin', true)
on conflict (username) do update
set role = 'admin', active = true, updated_at = now();

create unique index if not exists idx_couriers_username_unique on couriers (lower(username));
create index if not exists idx_products_barcode on products(barcode);
create index if not exists idx_products_active_deleted on products(active, deleted_at);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_launched_at on orders(launched_at);
create index if not exists idx_orders_phone on orders(phone);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_order_payments_order_id_status on order_payments(order_id, status);
create index if not exists idx_notifications_audience on notifications(audience);
create index if not exists idx_notifications_order_id on notifications(order_id);
create index if not exists idx_product_stock_movements_product_id on product_stock_movements(product_id);
create index if not exists idx_cash_sessions_status on cash_sessions(status);
create index if not exists idx_tab_accounts_status on tab_accounts(status);
create index if not exists idx_kit_items_kit_id on kit_items(kit_id);
create index if not exists idx_audit_logs_created_at on audit_logs(created_at);


-- Baixa/devolução atômica de estoque para evitar sobrescrever estoque em uso simultâneo.
-- A função não permite estoque negativo: se uma baixa deixar o produto abaixo de zero,
-- ela retorna falha e mantém o estoque original daquele produto.
create or replace function apply_product_stock_deltas(p_deltas jsonb)
returns jsonb
language plpgsql
as $$
declare
  failures jsonb := '[]'::jsonb;
  applied jsonb := '[]'::jsonb;
begin
  if p_deltas is null or jsonb_typeof(p_deltas) <> 'array' then
    return jsonb_build_object(
      'success', false,
      'failures', jsonb_build_array(jsonb_build_object('error', 'invalid_payload')),
      'applied', applied
    );
  end if;

  create temporary table if not exists tmp_product_stock_deltas (
    product_id bigint primary key,
    delta integer not null
  ) on commit drop;

  truncate table tmp_product_stock_deltas;

  insert into tmp_product_stock_deltas(product_id, delta)
  select product_id, sum(delta)::integer as delta
  from jsonb_to_recordset(p_deltas) as x(product_id bigint, delta integer)
  where product_id is not null
    and delta is not null
    and delta <> 0
  group by product_id;

  if not exists (select 1 from tmp_product_stock_deltas) then
    return jsonb_build_object('success', true, 'failures', failures, 'applied', applied);
  end if;

  -- Trava todos os produtos envolvidos antes de validar. Assim a operação é tudo-ou-nada:
  -- se qualquer item falhar, nenhum estoque é alterado.
  perform 1
  from products p
  join tmp_product_stock_deltas d on d.product_id = p.id
  order by p.id
  for update;

  select coalesce(jsonb_agg(jsonb_build_object('product_id', d.product_id, 'error', 'not_found')), '[]'::jsonb)
    into failures
    from tmp_product_stock_deltas d
    left join products p on p.id = d.product_id
    where p.id is null;

  select failures || coalesce(jsonb_agg(jsonb_build_object(
      'product_id', p.id,
      'error', 'insufficient_stock',
      'stock_before', coalesce(p.stock, 0),
      'delta', d.delta
    )), '[]'::jsonb)
    into failures
    from tmp_product_stock_deltas d
    join products p on p.id = d.product_id
    where coalesce(p.stock, 0) + d.delta < 0;

  if jsonb_array_length(failures) > 0 then
    return jsonb_build_object('success', false, 'failures', failures, 'applied', applied);
  end if;

  with before_update as (
    select p.id as product_id, coalesce(p.stock, 0) as stock_before, d.delta
    from products p
    join tmp_product_stock_deltas d on d.product_id = p.id
  ), updated as (
    update products p
    set stock = before_update.stock_before + before_update.delta,
        updated_at = now()
    from before_update
    where p.id = before_update.product_id
    returning p.id as product_id,
      before_update.stock_before,
      before_update.delta,
      p.stock as stock_after
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', product_id,
    'stock_before', stock_before,
    'delta', delta,
    'stock_after', stock_after
  )), '[]'::jsonb)
  into applied
  from updated;

  return jsonb_build_object('success', true, 'failures', failures, 'applied', applied);
end;
$$;

grant execute on function apply_product_stock_deltas(jsonb) to anon, authenticated;


-- Substituição transacional dos itens de kit. Evita o estado parcial "kit atualizado,
-- itens apagados e novos itens não inseridos" caso uma inserção falhe no meio.
create or replace function replace_kit_items(p_kit_id bigint, p_items jsonb)
returns jsonb
language plpgsql
as $$
declare
  inserted_count integer := 0;
begin
  if p_kit_id is null then
    return jsonb_build_object('success', false, 'error', 'missing_kit_id');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    return jsonb_build_object('success', false, 'error', 'invalid_items');
  end if;

  if not exists (select 1 from kits where id = p_kit_id) then
    return jsonb_build_object('success', false, 'error', 'kit_not_found');
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer)
    where product_id is null or quantity is null or quantity <= 0
  ) then
    return jsonb_build_object('success', false, 'error', 'invalid_item_row');
  end if;

  delete from kit_items where kit_id = p_kit_id;

  insert into kit_items(id, kit_id, product_id, quantity)
  select
    (extract(epoch from clock_timestamp()) * 1000000)::bigint + row_number() over (),
    p_kit_id,
    product_id,
    quantity
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer);

  get diagnostics inserted_count = row_count;

  return jsonb_build_object('success', true, 'inserted', inserted_count);
end;
$$;

grant execute on function replace_kit_items(bigint, jsonb) to anon, authenticated;


-- Substituição transacional dos itens de comanda/fiado. Evita apagar itens antigos
-- antes de confirmar que os novos itens foram gravados corretamente.
create or replace function replace_tab_account_items(p_tab_account_id bigint, p_items jsonb)
returns jsonb
language plpgsql
as $$
declare
  inserted_count integer := 0;
begin
  if p_tab_account_id is null then
    return jsonb_build_object('success', false, 'error', 'missing_tab_account_id');
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    return jsonb_build_object('success', false, 'error', 'invalid_items');
  end if;

  if not exists (select 1 from tab_accounts where id = p_tab_account_id) then
    return jsonb_build_object('success', false, 'error', 'tab_account_not_found');
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(product_id bigint, name text, quantity integer, price numeric, barcode text)
    where quantity is null or quantity <= 0
  ) then
    return jsonb_build_object('success', false, 'error', 'invalid_item_row');
  end if;

  delete from tab_account_items where tab_account_id = p_tab_account_id;

  insert into tab_account_items(tab_account_id, product_id, name, quantity, price, barcode)
  select
    p_tab_account_id,
    product_id,
    coalesce(nullif(name, ''), 'Produto'),
    quantity,
    coalesce(price, 0),
    coalesce(barcode, '')
  from jsonb_to_recordset(p_items) as x(product_id bigint, name text, quantity integer, price numeric, barcode text);

  get diagnostics inserted_count = row_count;

  return jsonb_build_object('success', true, 'inserted', inserted_count);
end;
$$;

grant execute on function replace_tab_account_items(bigint, jsonb) to anon, authenticated;

-- Fase 51 / 6.0.38: remove aprovação manual de pedidos do aplicativo.
-- Pedidos novos entram diretamente como Aguardando retirada.
-- Pedidos antigos que ainda estejam aguardando aprovação são liberados sem perder histórico.
update orders
set
  status = 'Aguardando retirada',
  needs_store_approval = false,
  store_order_approved = true,
  approved_at = coalesce(approved_at, updated_at, created_at, now())
where status = 'Aguardando aprovação do pedido'
   or coalesce(needs_store_approval, false) = true;

alter table orders alter column needs_store_approval set default false;
alter table orders alter column store_order_approved set default true;

-- Fase 52 - Fila de impressão para o aplicativo desktop Electron.
create table if not exists print_jobs (
  id text primary key,
  source text not null default 'unknown',
  source_id text not null default '',
  print_type text not null default 'kitchen',
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  printer_name text default '',
  copies integer not null default 1,
  attempts integer not null default 0,
  error_message text default '',
  worker_id text default '',
  printing_at timestamp with time zone,
  printed_at timestamp with time zone,
  failed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table print_jobs add column if not exists source text not null default 'unknown';
alter table print_jobs add column if not exists source_id text not null default '';
alter table print_jobs add column if not exists print_type text not null default 'kitchen';
alter table print_jobs add column if not exists status text not null default 'pending';
alter table print_jobs add column if not exists payload jsonb not null default '{}'::jsonb;
alter table print_jobs add column if not exists printer_name text default '';
alter table print_jobs add column if not exists copies integer not null default 1;
alter table print_jobs add column if not exists attempts integer not null default 0;
alter table print_jobs add column if not exists error_message text default '';
alter table print_jobs add column if not exists worker_id text default '';
alter table print_jobs add column if not exists locked_by text default '';
alter table print_jobs add column if not exists printing_at timestamp with time zone;
alter table print_jobs add column if not exists printed_at timestamp with time zone;
alter table print_jobs add column if not exists failed_at timestamp with time zone;
alter table print_jobs add column if not exists cancelled_at timestamp with time zone;
alter table print_jobs add column if not exists created_at timestamp with time zone default now();
alter table print_jobs add column if not exists updated_at timestamp with time zone default now();

create index if not exists idx_print_jobs_status_created_at on print_jobs(status, created_at);
create index if not exists idx_print_jobs_source on print_jobs(source, source_id);
create unique index if not exists idx_print_jobs_unique_source_type on print_jobs(source, source_id, print_type);

drop function if exists claim_pending_print_jobs(text, integer);
drop function if exists claim_pending_print_jobs(text, integer, text[], text[]);

create or replace function claim_pending_print_jobs(
  p_worker_id text,
  p_limit integer default 10,
  p_sources text[] default null,
  p_print_types text[] default null
)
returns setof print_jobs
language plpgsql
security definer
as $$
begin
  return query
  with picked as (
    select id
      from print_jobs
     where status in ('pending', 'failed')
       and cancelled_at is null
       and (status = 'pending' or attempts < 5)
       and (p_sources is null or source = any(p_sources))
       and (p_print_types is null or print_type = any(p_print_types))
     order by created_at asc
     limit greatest(1, least(coalesce(p_limit, 10), 50))
     for update skip locked
  )
  update print_jobs pj
     set status = 'printing',
         worker_id = coalesce(nullif(p_worker_id, ''), 'electron-desktop'),
         locked_by = coalesce(nullif(p_worker_id, ''), 'electron-desktop'),
         printing_at = now(),
         attempts = coalesce(pj.attempts, 0) + 1,
         error_message = '',
         updated_at = now()
    from picked
   where pj.id = picked.id
  returning pj.*;
end;
$$;

create or replace function mark_print_job_printed(p_job_id text, p_printer_name text default '')
returns print_jobs
language plpgsql
security definer
as $$
declare
  updated_job print_jobs;
begin
  update print_jobs
     set status = 'printed',
         printer_name = coalesce(nullif(p_printer_name, ''), printer_name),
         printed_at = now(),
         error_message = '',
         updated_at = now()
   where id::text = p_job_id
   returning * into updated_job;
  return updated_job;
end;
$$;

create or replace function mark_print_job_failed(p_job_id text, p_error_message text default '')
returns print_jobs
language plpgsql
security definer
as $$
declare
  updated_job print_jobs;
begin
  update print_jobs
     set status = 'failed',
         failed_at = now(),
         error_message = left(coalesce(p_error_message, 'Falha de impressão'), 1000),
         updated_at = now()
   where id::text = p_job_id
   returning * into updated_job;
  return updated_job;
end;
$$;

update orders
   set status = 'Aguardando retirada',
       needs_store_approval = false,
       store_order_approved = true,
       approved_at = coalesce(approved_at, updated_at, created_at, now()),
       updated_at = now()
 where status = 'Aguardando aprovação do pedido'
    or needs_store_approval is true
    or store_order_approved is not true;

-- Fase 55 / 6.0.43:
-- A estrutura de print_jobs permanece compatível com a Fase 52.
-- O payload gravado pelo aplicativo passa a incluir ticket.html, ticket.lines e ticket.sections
-- para os modelos de cozinha, entrega e balcão que serão consumidos pelo Electron.


-- Fase 55 / 6.0.43:
-- O Electron Desktop agora consome print_jobs automaticamente.
-- claim_pending_print_jobs aceita filtros de source/print_type para respeitar as regras locais
-- Pedido do app: cozinha + entrega; PDV Entregas: cozinha + entrega; PDV Balcão: balcão.


-- Fase 56 / 6.0.44:
-- Não altera schema. Mantém a fila print_jobs e funções da 6.0.43 para o instalador Windows Electron.

-- Fase 57 / 6.0.45:
-- Central de impressão operacional, heartbeat do computador de impressão
-- e rotina para recuperar jobs travados em printing.

create table if not exists print_workers (
  worker_id text primary key,
  computer_name text default '',
  status text not null default 'offline',
  printer_name text default '',
  app_version text default '',
  last_seen_at timestamp with time zone default now(),
  last_error text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table print_workers add column if not exists worker_id text;
alter table print_workers add column if not exists computer_name text default '';
alter table print_workers add column if not exists status text not null default 'offline';
alter table print_workers add column if not exists printer_name text default '';
alter table print_workers add column if not exists app_version text default '';
alter table print_workers add column if not exists last_seen_at timestamp with time zone default now();
alter table print_workers add column if not exists last_error text default '';
alter table print_workers add column if not exists created_at timestamp with time zone default now();
alter table print_workers add column if not exists updated_at timestamp with time zone default now();

create unique index if not exists idx_print_workers_worker_id on print_workers(worker_id);
create index if not exists idx_print_workers_last_seen_at on print_workers(last_seen_at desc);

alter table print_workers enable row level security;

drop policy if exists "print_workers_select_all" on print_workers;
create policy "print_workers_select_all"
  on print_workers for select
  using (true);

drop policy if exists "print_workers_insert_all" on print_workers;
create policy "print_workers_insert_all"
  on print_workers for insert
  with check (true);

drop policy if exists "print_workers_update_all" on print_workers;
create policy "print_workers_update_all"
  on print_workers for update
  using (true)
  with check (true);

create or replace function upsert_print_worker_heartbeat(
  p_worker_id text,
  p_computer_name text default '',
  p_status text default 'online',
  p_printer_name text default '',
  p_app_version text default '',
  p_last_error text default ''
)
returns print_workers
language plpgsql
security definer
as $$
declare
  updated_worker print_workers;
begin
  insert into print_workers (
    worker_id,
    computer_name,
    status,
    printer_name,
    app_version,
    last_seen_at,
    last_error,
    created_at,
    updated_at
  ) values (
    coalesce(nullif(p_worker_id, ''), 'barbosas-desktop'),
    coalesce(p_computer_name, ''),
    coalesce(nullif(p_status, ''), 'online'),
    coalesce(p_printer_name, ''),
    coalesce(p_app_version, ''),
    now(),
    coalesce(p_last_error, ''),
    now(),
    now()
  )
  on conflict (worker_id) do update
     set computer_name = excluded.computer_name,
         status = excluded.status,
         printer_name = excluded.printer_name,
         app_version = excluded.app_version,
         last_seen_at = now(),
         last_error = excluded.last_error,
         updated_at = now()
  returning * into updated_worker;

  return updated_worker;
end;
$$;

create or replace function reset_stale_print_jobs(p_minutes integer default 10)
returns setof print_jobs
language plpgsql
security definer
as $$
begin
  return query
  update print_jobs
     set status = 'pending',
         worker_id = '',
         locked_by = '',
         printing_at = null,
         error_message = 'Job voltou para pendente automaticamente: impressão ficou travada.',
         updated_at = now()
   where status = 'printing'
     and printing_at is not null
     and printing_at < now() - make_interval(mins => greatest(coalesce(p_minutes, 10), 1))
  returning *;
end;
$$;


-- Fase 58: reforço de cupons e estoque seguro.
-- Cria/ajusta public.coupons para evitar erro PGRST205 no carregamento de cupons.
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text default '',
  discount_type text default 'fixed',
  discount_value numeric default 0,
  minimum_order_value numeric default 0,
  max_discount numeric default 0,
  usage_limit integer default 0,
  used_count integer default 0,
  start_date date,
  end_date date,
  active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.coupons add column if not exists code text;
alter table public.coupons add column if not exists description text default '';
alter table public.coupons add column if not exists discount_type text default 'fixed';
alter table public.coupons add column if not exists discount_value numeric default 0;
alter table public.coupons add column if not exists minimum_order_value numeric default 0;
alter table public.coupons add column if not exists max_discount numeric default 0;
alter table public.coupons add column if not exists usage_limit integer default 0;
alter table public.coupons add column if not exists used_count integer default 0;
alter table public.coupons add column if not exists start_date date;
alter table public.coupons add column if not exists end_date date;
alter table public.coupons add column if not exists active boolean default true;
alter table public.coupons add column if not exists created_at timestamp with time zone default now();
alter table public.coupons add column if not exists updated_at timestamp with time zone default now();

create unique index if not exists idx_coupons_code on public.coupons(code);
create index if not exists idx_coupons_active on public.coupons(active);

alter table public.coupons enable row level security;

drop policy if exists "coupons_select_all" on public.coupons;
create policy "coupons_select_all" on public.coupons for select using (true);

drop policy if exists "coupons_insert_all" on public.coupons;
create policy "coupons_insert_all" on public.coupons for insert with check (true);

drop policy if exists "coupons_update_all" on public.coupons;
create policy "coupons_update_all" on public.coupons for update using (true) with check (true);

drop policy if exists "coupons_delete_all" on public.coupons;
create policy "coupons_delete_all" on public.coupons for delete using (true);

-- Fase 58: função atômica de estoque compatível com ambientes que bloqueiam DELETE sem WHERE.
-- Usa TRUNCATE em tabela temporária em vez de DELETE sem WHERE.
create or replace function public.apply_product_stock_deltas(p_deltas jsonb)
returns jsonb
language plpgsql
security definer
as $$
declare
  failures jsonb := '[]'::jsonb;
  applied jsonb := '[]'::jsonb;
begin
  if p_deltas is null or jsonb_typeof(p_deltas) <> 'array' then
    return jsonb_build_object(
      'success', false,
      'failures', jsonb_build_array(jsonb_build_object('error', 'invalid_payload')),
      'applied', applied
    );
  end if;

  create temporary table if not exists tmp_product_stock_deltas (
    product_id bigint primary key,
    delta integer not null
  ) on commit drop;

  truncate table tmp_product_stock_deltas;

  insert into tmp_product_stock_deltas(product_id, delta)
  select product_id, sum(delta)::integer as delta
  from jsonb_to_recordset(p_deltas) as x(product_id bigint, delta integer)
  where product_id is not null
    and delta is not null
    and delta <> 0
  group by product_id;

  if not exists (select 1 from tmp_product_stock_deltas) then
    return jsonb_build_object('success', true, 'failures', failures, 'applied', applied);
  end if;

  perform 1
  from public.products p
  join tmp_product_stock_deltas d on d.product_id = p.id
  order by p.id
  for update;

  select coalesce(jsonb_agg(jsonb_build_object('product_id', d.product_id, 'error', 'not_found')), '[]'::jsonb)
    into failures
    from tmp_product_stock_deltas d
    left join public.products p on p.id = d.product_id
    where p.id is null;

  select failures || coalesce(jsonb_agg(jsonb_build_object(
      'product_id', p.id,
      'error', 'insufficient_stock',
      'stock_before', coalesce(p.stock, 0),
      'delta', d.delta
    )), '[]'::jsonb)
    into failures
    from tmp_product_stock_deltas d
    join public.products p on p.id = d.product_id
    where coalesce(p.stock, 0) + d.delta < 0;

  if jsonb_array_length(failures) > 0 then
    return jsonb_build_object('success', false, 'failures', failures, 'applied', applied);
  end if;

  with before_update as (
    select p.id as product_id, coalesce(p.stock, 0) as stock_before, d.delta
    from public.products p
    join tmp_product_stock_deltas d on d.product_id = p.id
  ), updated as (
    update public.products p
    set stock = before_update.stock_before + before_update.delta,
        updated_at = now()
    from before_update
    where p.id = before_update.product_id
    returning p.id as product_id,
      before_update.stock_before,
      before_update.delta,
      p.stock as stock_after
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', product_id,
    'stock_before', stock_before,
    'delta', delta,
    'stock_after', stock_after
  )), '[]'::jsonb)
  into applied
  from updated;

  return jsonb_build_object('success', true, 'failures', failures, 'applied', applied);
end;
$$;

grant execute on function public.apply_product_stock_deltas(jsonb) to anon, authenticated;

-- Fase 59 / 6.0.47 - Impressão automática definitiva para pedidos do app.
-- Garante que a fila print_jobs aceite bancos com id numérico identity e bancos antigos com id textual.
-- O app passa a deduplicar por origem + pedido + tipo de via.

alter table public.print_jobs add column if not exists source text not null default 'unknown';
alter table public.print_jobs add column if not exists source_id text not null default '';
alter table public.print_jobs add column if not exists print_type text not null default 'kitchen';
alter table public.print_jobs add column if not exists status text not null default 'pending';
alter table public.print_jobs add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.print_jobs add column if not exists copies integer not null default 1;
alter table public.print_jobs add column if not exists attempts integer not null default 0;
alter table public.print_jobs add column if not exists error_message text default '';
alter table public.print_jobs add column if not exists locked_by text default '';
alter table public.print_jobs add column if not exists worker_id text default '';
alter table public.print_jobs add column if not exists printing_at timestamp with time zone;
alter table public.print_jobs add column if not exists printed_at timestamp with time zone;
alter table public.print_jobs add column if not exists failed_at timestamp with time zone;
alter table public.print_jobs add column if not exists cancelled_at timestamp with time zone;
alter table public.print_jobs add column if not exists created_at timestamp with time zone default now();
alter table public.print_jobs add column if not exists updated_at timestamp with time zone default now();

-- Remove duplicidades antigas antes de criar a trava lógica da fila.
-- Mantém, para cada source/source_id/print_type, o registro impresso mais recente quando existir;
-- caso contrário, mantém o mais recente.
with ranked_print_jobs as (
  select
    ctid,
    row_number() over (
      partition by source, source_id, print_type
      order by
        case when status = 'printed' then 0 else 1 end,
        coalesce(printed_at, updated_at, created_at, now()) desc
    ) as rn
  from public.print_jobs
  where coalesce(source, '') <> ''
    and coalesce(source_id, '') <> ''
    and coalesce(print_type, '') <> ''
)
delete from public.print_jobs pj
using ranked_print_jobs r
where pj.ctid = r.ctid
  and r.rn > 1;

create unique index if not exists idx_print_jobs_unique_source_type
on public.print_jobs(source, source_id, print_type);

create index if not exists idx_print_jobs_status_created_at
on public.print_jobs(status, created_at);

create index if not exists idx_print_jobs_source
on public.print_jobs(source, source_id);

-- Fase 60 / 6.0.48 - Conversão para lanchonete.
-- Prepara o cardápio para adicionais, ingredientes removíveis e observação por item.

alter table public.products add column if not exists product_type text default 'produto';
alter table public.products add column if not exists ingredients jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists removable_ingredients jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists default_addons jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists allow_item_notes boolean not null default true;

create index if not exists idx_products_product_type
on public.products(product_type);

-- Mantém histórico de fiados/comandas, mas sinaliza que a operação nova é lanchonete.
-- As telas de fiado/comanda foram removidas da navegação do aplicativo na versão 6.0.48.

create table if not exists public.menu_addons (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  category text default '',
  applies_to_product_ids jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.menu_addons add column if not exists name text;
alter table public.menu_addons add column if not exists price numeric not null default 0;
alter table public.menu_addons add column if not exists category text default '';
alter table public.menu_addons add column if not exists applies_to_product_ids jsonb not null default '[]'::jsonb;
alter table public.menu_addons add column if not exists active boolean not null default true;
alter table public.menu_addons add column if not exists created_at timestamp with time zone default now();
alter table public.menu_addons add column if not exists updated_at timestamp with time zone default now();

create index if not exists idx_menu_addons_active
on public.menu_addons(active);

alter table public.menu_addons enable row level security;

drop policy if exists "menu_addons_select_all" on public.menu_addons;
create policy "menu_addons_select_all"
on public.menu_addons
for select
using (true);

drop policy if exists "menu_addons_insert_all" on public.menu_addons;
create policy "menu_addons_insert_all"
on public.menu_addons
for insert
with check (true);

drop policy if exists "menu_addons_update_all" on public.menu_addons;
create policy "menu_addons_update_all"
on public.menu_addons
for update
using (true)
with check (true);
