-- Barbosa's Delivery - Fase 24
-- Usuários da loja e permissões por perfil.
-- Rode no SQL Editor do Supabase antes de usar a aba Acessos.

create table if not exists store_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  email text unique,
  password text not null,
  role text not null default 'operador',
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table store_users add column if not exists name text;
alter table store_users add column if not exists username text;
alter table store_users add column if not exists email text;
alter table store_users add column if not exists password text;
alter table store_users add column if not exists role text default 'operador';
alter table store_users add column if not exists active boolean default true;
alter table store_users add column if not exists created_at timestamp with time zone default now();
alter table store_users add column if not exists updated_at timestamp with time zone default now();

create unique index if not exists idx_store_users_username_unique on store_users (lower(username));
create unique index if not exists idx_store_users_email_unique on store_users (lower(email)) where email is not null and email <> '';
create index if not exists idx_store_users_active on store_users(active);
create index if not exists idx_store_users_role on store_users(role);

insert into store_users (name, username, email, password, role, active)
values ('Administrador da loja', 'gabrieladmin', null, 'B4rb@2026!', 'admin', true)
on conflict (username) do update
set role = 'admin', active = true, updated_at = now();

-- IMPORTANTE:
-- Depois de rodar, entre com:
-- usuário: gabrieladmin
-- senha: B4rb@2026!
-- Troque a senha pela aba Acessos.
