-- Barbosa's Delivery - Migração final de produção 6.0.28
-- Rode este arquivo no SQL Editor do Supabase antes do deploy final.
-- Ele cria as tabelas principais caso o banco esteja novo e reforça colunas usadas pelo app.

create table if not exists products (
  id bigint primary key,
  name text not null default '',
  category text default '',
  price numeric not null default 0,
  cost numeric not null default 0,
  stock integer not null default 0,
  min_stock integer not null default 0,
  barcode text,
  expiration_date date,
  image_url text default '',
  has_variants boolean default false,
  variants jsonb default '[]'::jsonb,
  active boolean default true,
  deleted_at timestamp with time zone,
  paused_until timestamp with time zone,
  pause_reason text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists clients (
  id bigint primary key,
  name text not null default '',
  phone text default '',
  phone_digits text,
  cep text default '',
  street text default '',
  number text default '',
  district text default '',
  city text default '',
  state text default '',
  reference text default '',
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists couriers (
  id bigint primary key,
  name text not null default '',
  username text not null,
  password text not null default '',
  motorcycle_type text default 'Moto própria',
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists orders (
  id text primary key,
  cash_session_id text,
  origin_type text,
  tab_account_id bigint,
  order_type text default 'delivery',
  client text default '',
  customer_name text,
  phone text default '',
  address text default '',
  payment text default 'Pix',
  payment_status text default 'pending',
  payment_confirmed_at timestamp with time zone,
  payment_confirmed_by text,
  reopened_at timestamp with time zone,
  reopened_by text,
  reopen_reason text,
  change_for numeric,
  products_total numeric default 0,
  delivery_fee numeric default 0,
  discount numeric default 0,
  coupon_code text,
  coupon_id bigint,
  coupon_discount numeric default 0,
  courier_fee numeric default 0,
  store_fee numeric default 0,
  motorcycle_type text,
  value numeric default 0,
  estimated_delivery_minutes integer default 0,
  whatsapp_status text default 'not_sent',
  whatsapp_opened_at timestamp with time zone,
  whatsapp_sent_at timestamp with time zone,
  whatsapp_message text,
  status text default 'Aguardando retirada',
  origin text default 'store',
  needs_store_approval boolean default false,
  store_order_approved boolean default true,
  approved_at timestamp with time zone,
  reference text,
  delivery_district text,
  delivery_zone text,
  courier_username text default 'ALL',
  courier_name text default 'Todos os motoboys',
  notes text,
  picked_up_by_username text,
  picked_up_by_name text,
  picked_up_at timestamp with time zone,
  delivered_by_username text,
  delivered_by_name text,
  delivered_at timestamp with time zone,
  owner_approved boolean default false,
  owner_approved_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  accepted_by_username text,
  accepted_by_name text,
  accepted_at timestamp with time zone,
  refused_by_username text,
  refused_at timestamp with time zone,
  finalized_at timestamp with time zone,
  finalized_by text,
  problem_reason text,
  problem_at timestamp with time zone,
  proof_url text,
  delay_alerted_at timestamp with time zone,
  launched_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text,
  cash_session_id text,
  product_id bigint,
  name text default '',
  product_name text,
  quantity integer not null default 0,
  price numeric not null default 0,
  barcode text,
  is_kit boolean default false,
  kit_id bigint,
  created_at timestamp with time zone default now()
);

create table if not exists order_payments (
  id bigint generated by default as identity primary key,
  order_id text,
  cash_session_id text,
  method text not null default 'Outro',
  amount numeric not null default 0,
  status text not null default 'paid',
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists promotions (
  id bigint primary key,
  title text not null default '',
  description text default '',
  product_id bigint,
  badge text default 'Promoção da loja',
  image_url text default '',
  discount_percent numeric default 0,
  promotional_price numeric default 0,
  start_date date,
  end_date date,
  active boolean default true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists coupons (
  id bigint primary key,
  code text not null unique,
  description text default '',
  discount_type text not null default 'fixed',
  discount_value numeric not null default 0,
  minimum_order_value numeric not null default 0,
  max_discount numeric not null default 0,
  usage_limit integer not null default 0,
  used_count integer not null default 0,
  start_date date,
  end_date date,
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists kits (
  id bigint primary key,
  name text not null default '',
  description text default '',
  price numeric not null default 0,
  end_date date,
  active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists kit_items (
  id bigint primary key,
  kit_id bigint,
  product_id bigint,
  quantity integer not null default 1,
  created_at timestamp with time zone default now()
);

create table if not exists store_settings (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists store_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  email text unique,
  password text not null,
  role text not null default 'operador',
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  type text,
  title text,
  message text,
  audience text,
  order_id text,
  courier_username text,
  customer_phone text,
  read_at timestamp with time zone,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table if not exists product_stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint,
  order_id text,
  cash_session_id text,
  movement_type text not null default 'manual_adjustment',
  quantity integer not null default 0,
  stock_before integer not null default 0,
  stock_after integer not null default 0,
  reason text,
  created_by text,
  created_at timestamp with time zone default now()
);

create table if not exists cash_sessions (
  id text primary key default gen_random_uuid()::text,
  status text not null default 'open',
  opening_amount numeric default 0,
  opened_at timestamp with time zone default now(),
  opened_by text,
  closed_at timestamp with time zone,
  closed_by text,
  total_sold numeric default 0,
  total_received numeric default 0,
  counted_cash numeric default 0,
  difference numeric default 0,
  pix_total numeric default 0,
  cash_total numeric default 0,
  debit_total numeric default 0,
  credit_total numeric default 0,
  pending_total numeric default 0,
  cancelled_total numeric default 0,
  closing_snapshot jsonb,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists cash_movements (
  id bigint primary key,
  movement_type text,
  type text,
  value numeric default 0,
  amount numeric default 0,
  reason text,
  opened_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists tab_accounts (
  id bigint primary key,
  customer_name text not null default 'Cliente',
  phone text default '',
  credit_limit numeric default 0,
  payment text default 'Dinheiro',
  status text default 'open',
  total numeric default 0,
  opened_at timestamp with time zone default now(),
  closed_at timestamp with time zone,
  closed_by text,
  cash_session_id text,
  items_json text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists tab_account_items (
  id bigint generated by default as identity primary key,
  tab_account_id bigint,
  product_id bigint,
  name text default '',
  quantity integer not null default 1,
  price numeric not null default 0,
  barcode text,
  created_at timestamp with time zone default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_type text not null default 'system',
  user_name text not null default 'sistema',
  action text not null,
  entity text not null,
  entity_id text,
  before_json jsonb,
  after_json jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists app_errors (
  id bigint generated by default as identity primary key,
  source text not null,
  message text,
  stack text,
  metadata jsonb,
  created_at timestamp with time zone default now()
);

-- Reforço de colunas caso o banco já existisse com esquema antigo.
alter table products add column if not exists active boolean default true;
alter table products add column if not exists deleted_at timestamp with time zone;
alter table products add column if not exists has_variants boolean default false;
alter table products add column if not exists variants jsonb default '[]'::jsonb;
alter table products add column if not exists paused_until timestamp with time zone;
alter table products add column if not exists pause_reason text default '';
alter table products add column if not exists min_stock integer default 0;
alter table products add column if not exists barcode text;
alter table products add column if not exists image_url text default '';

alter table clients add column if not exists active boolean default true;
alter table clients add column if not exists deleted_at timestamp with time zone;
alter table clients add column if not exists phone_digits text;

alter table couriers add column if not exists active boolean default true;
alter table couriers add column if not exists deleted_at timestamp with time zone;
alter table couriers add column if not exists motorcycle_type text default 'Moto própria';

alter table kits add column if not exists active boolean default true;
alter table kit_items add column if not exists kit_id bigint;
alter table kit_items add column if not exists product_id bigint;
alter table kit_items add column if not exists quantity integer default 1;

insert into store_settings (id, settings)
values ('default', '{}'::jsonb)
on conflict (id) do nothing;

insert into store_users (name, username, email, password, role, active)
values ('Administrador da loja', 'gabrieladmin', null, 'B4rb@2026!', 'admin', true)
on conflict (username) do update
set role = 'admin', active = true, updated_at = now();

create unique index if not exists idx_couriers_username_unique on couriers (lower(username));
create index if not exists idx_products_barcode on products(barcode);
create index if not exists idx_products_active_deleted on products(active, deleted_at);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_launched_at on orders(launched_at);
create index if not exists idx_orders_phone on orders(phone);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_order_payments_order_id_status on order_payments(order_id, status);
create index if not exists idx_notifications_audience on notifications(audience);
create index if not exists idx_notifications_order_id on notifications(order_id);
create index if not exists idx_product_stock_movements_product_id on product_stock_movements(product_id);
create index if not exists idx_cash_sessions_status on cash_sessions(status);
create index if not exists idx_tab_accounts_status on tab_accounts(status);
create index if not exists idx_kit_items_kit_id on kit_items(kit_id);
create index if not exists idx_audit_logs_created_at on audit_logs(created_at);


-- Baixa/devolução atômica de estoque para evitar sobrescrever estoque em uso simultâneo.
-- A função não permite estoque negativo: se uma baixa deixar o produto abaixo de zero,
-- ela retorna falha e mantém o estoque original daquele produto.
create or replace function apply_product_stock_deltas(p_deltas jsonb)
returns jsonb
language plpgsql
as $$
declare
  delta_rec record;
  current_stock integer;
  updated_count integer;
  failures jsonb := '[]'::jsonb;
  applied jsonb := '[]'::jsonb;
begin
  if p_deltas is null or jsonb_typeof(p_deltas) <> 'array' then
    return jsonb_build_object('success', false, 'failures', jsonb_build_array(jsonb_build_object('error', 'invalid_payload')), 'applied', applied);
  end if;

  for delta_rec in
    select * from jsonb_to_recordset(p_deltas) as x(product_id bigint, delta integer)
  loop
    if delta_rec.product_id is null or delta_rec.delta is null or delta_rec.delta = 0 then
      continue;
    end if;

    select coalesce(stock, 0)
      into current_stock
      from products
      where id = delta_rec.product_id
      for update;

    if current_stock is null then
      failures = failures || jsonb_build_object('product_id', delta_rec.product_id, 'error', 'not_found');
      continue;
    end if;

    if current_stock + delta_rec.delta < 0 then
      failures = failures || jsonb_build_object(
        'product_id', delta_rec.product_id,
        'error', 'insufficient_stock',
        'stock_before', current_stock,
        'delta', delta_rec.delta
      );
      continue;
    end if;

    update products
    set stock = current_stock + delta_rec.delta,
        updated_at = now()
    where id = delta_rec.product_id;

    get diagnostics updated_count = row_count;
    if updated_count = 0 then
      failures = failures || jsonb_build_object('product_id', delta_rec.product_id, 'error', 'not_found');
    else
      applied = applied || jsonb_build_object(
        'product_id', delta_rec.product_id,
        'stock_before', current_stock,
        'delta', delta_rec.delta,
        'stock_after', current_stock + delta_rec.delta
      );
    end if;
  end loop;

  return jsonb_build_object('success', jsonb_array_length(failures) = 0, 'failures', failures, 'applied', applied);
end;
$$;

grant execute on function apply_product_stock_deltas(jsonb) to anon, authenticated;
